version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yarn install  # Or `npm install` if you're using npm

  build:
    commands:
      - echo "Building the Gatsby project..."
      - yarn build  # Or `npm run build` if you're using npm
      - echo "Listing files in the public directory:"
      - ls -la public/  # List the contents of the public directory to verify the build output

  post_build:
    commands:
      - echo "Checking AWS CLI version"
      - aws --version
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id EBY5A4SBU2CE0 --paths "/*"

artifacts:
  files:
    - '**/*'  # All files from the public folder
  base-directory: public  # Gatsby outputs the static files in the public directory
  discard-paths: no
