version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yarn install  # Or `npm install` if you're using npm

  build:
    commands:
      - echo "Building the Gatsby project..."
      - yarn build  # Or npm run build if you're using npm
      - echo "Zipping build output..."
      - mkdir -p build  # Create the build directory if it doesn't exist
      - zip -r build/output.zip public/  # Zip the contents of the public directory and place it inside the build folder
      - echo "Listing files in the build directory:"
      - ls -la build/  # List the contents of the build directory to verify

  post_build:
    commands:
      - echo "Checking AWS CLI version"
      - aws --version
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id EBY5A4SBU2CE0 --paths "/*"

artifacts:
  files:
    - 'output.zip'  # Reference the file correctly
  base-directory: build  # Ensure the base-directory points to where the zip file is located
  discard-paths: no
