version: 0.2  # Adjusted to the latest version

phases:
  install:
    commands:
      - 'touch .npmignore'  # Avoid .npmignore errors
      - 'yarn global add gatsby-cli'  # Install Gatsby globally using Yarn
  
  pre_build:
    commands:
      - 'yarn install'  # Install project dependencies using Yarn
  
  build:
    commands:
      - 'yarn build'  # Run the Gatsby build using Yarn
  
  post_build:
    commands:
      - 'aws s3 sync "public/" "s3://mkrog.com" --delete --acl "public-read"'  # Sync build output to S3
      - 'aws cloudfront create-invalidation --distribution-id EBY5A4SBU2CE0 --paths "/*"'  # Invalidate CloudFront cache (optional)

artifacts:
  base-directory: public  # Specify the Gatsby output folder
  files:
    - '**/*'  # Include all files in the `public` folder
  discard-paths: yes  # Flatten the directory structure
