version: 0.2

phases:
  install:
    commands:
      - 'touch .npmignore'  # Prevent .npmignore issues
      - 'yarn global add gatsby-cli'  # Install Gatsby CLI globally
  
  pre_build:
    commands:
      - 'yarn install'  # Install dependencies
  
  build:
    commands:
      - 'yarn build'  # Build the Gatsby project
  
  post_build:
  commands:
    - echo "Deploying to S3..."
    - 'aws s3 sync public/ s3://mkrog.com/ --delete'  # Removed the --acl flag
    - 'aws cloudfront create-invalidation --distribution-id EBY5A4SBU2CE0 --paths "/*"'  # Invalidate CloudFront cache (optional)

artifacts:
  files:
    - '**/*'  # Include everything in the public folder (for future use if needed)
  base-directory: public
  discard-paths: yes  # Flatten the directory structur