version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yarn install  # Or use yarn if your project uses it
  build:
    commands:
      - echo Building the project...
      - npm run build  # This runs the build script in your package.json
  post_build:
    commands:
      - echo "Check AWS CLI version"
      - aws --version
      - echo "Invalidate CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id EBY5A4SBU2CE0 --paths "/*"


artifacts:
  files:
    - '**/*'  # You can change this to your specific build output
  base-directory: build  # This should be the directory where your build artifacts are located
  discard-paths: no
